### PR TITLE
Add daemon override option

### PR DESCRIPTION
**Pull request by sparkym3**
Add more flexibility to workflows and support older devices.

### CODE REVIEW

**Comment by cm-gerrit** [comment]
Hi there;

This is an automated reply, to let you know CyanogenMod doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at http://review.cyanogenmod.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.cyanogenmod.org/wiki/Howto:_Gerrit

Thanks!

**Comment by koush** [comment]
The daemon is not used in older versions anyways?

**Comment by sparkym3** [comment]
I only say older devices (versions of Android) as in they would still let the user do things without running a daemon, if they so choose.  This just seems like a nice thing to have for those who use it at a more basic level (terminal emulator) and don't run apps requiring su.

**Comment by cm-gerrit** [comment]
Hi there;

This is an automated reply, to let you know CyanogenMod doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at http://review.cyanogenmod.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.cyanogenmod.org/wiki/Howto:_Gerrit

Thanks!

**Pull request closed without merging**
